"""
Utility functions for the accounts app.

This module provides reusable helper functions for user management,
including automatic username generation with collision detection,
and profile photo processing.
"""

import re
import unicodedata
from datetime import datetime
from io import BytesIO

from django.apps import apps
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.utils.translation import gettext_lazy as _

try:
    from PIL import Image
    HAS_PILLOW = True
except ImportError:
    HAS_PILLOW = False


def generate_unique_username(first_name: str, last_name: str, year: int = None) -> str:
    """
    Generate a unique username from a user's first and last name.

    The username is generated by:
    1. Removing all spaces from the combined full name
    2. Appending the registration year (4 digits)
    3. Appending a sequential number (3 digits, zero-padded)

    Example: David Okonkwo, 2026, 1st user -> DavidOkonkwo2026001

    Args:
        first_name: The user's first name.
        last_name: The user's last name.
        year: The registration year (defaults to current year).

    Returns:
        A unique, never-before-used username string.
    """
    UserModel = get_user_model()

    if year is None:
        year = datetime.now().year

    # Step 1: Normalize unicode and remove spaces
    base = f"{first_name} {last_name}".strip()
    base = unicodedata.normalize("NFKD", base)
    base = base.encode("ascii", "ignore").decode("ascii")
    base = re.sub(r"\s+", "", base)  # Remove all spaces
    base = re.sub(r"[^a-zA-Z0-9]", "", base)  # Remove special characters

    # Step 2: Ensure we have at least some characters
    if not base:
        base = "User"

    # Step 3: Find the next sequential number for this year+base combination
    prefix = f"{base}{year}"
    existing_count = UserModel.objects.filter(username__startswith=prefix).count()
    seq = existing_count + 1

    # Step 4: Generate username with collision detection
    max_attempts = 100
    for _ in range(max_attempts):
        username = f"{prefix}{seq:03d}"
        if not UserModel.objects.filter(username=username).exists():
            return username
        seq += 1

    # Fallback (extremely unlikely): use timestamp as suffix
    import time
    return f"{prefix}{int(time.time())}"


def generate_unique_username_legacy(first_name: str, last_name: str) -> str:
    """
    Legacy username generator for backwards compatibility.
    Uses random 4-digit suffix.
    """
    UserModel = get_user_model()

    base = f"{first_name} {last_name}".lower()
    base = unicodedata.normalize("NFKD", base)
    base = base.encode("ascii", "ignore").decode("ascii")
    base = re.sub(r"[^a-z0-9]", "", base)

    if not base:
        base = "user"

    max_attempts = 100
    for _ in range(max_attempts):
        import secrets
        suffix = secrets.randbelow(9000) + 1000
        username = f"{base}{suffix}"
        if not UserModel.objects.filter(username=username).exists():
            return username

    import time
    return f"{base}{int(time.time())}"


def process_profile_photo(uploaded_file):
    """
    Process an uploaded profile photo:
    - Resize to max 500x500 while maintaining aspect ratio
    - Crop to square from center
    - Convert to RGB for JPEG compatibility
    - Optimize and compress
    
    Returns a ContentFile with the processed image, or the original file
    if Pillow is not available or processing fails.
    """
    if not HAS_PILLOW:
        return uploaded_file

    try:
        image = Image.open(uploaded_file)
        
        # Convert to RGB if necessary (e.g., RGBA -> RGB for JPEG)
        if image.mode in ('RGBA', 'LA', 'P'):
            background = Image.new('RGB', image.size, (255, 255, 255))
            if image.mode == 'P':
                image = image.convert('RGBA')
            background.paste(image, mask=image.split()[-1] if image.mode in ('RGBA', 'LA') else None)
            image = background
        elif image.mode != 'RGB':
            image = image.convert('RGB')
        
        # Get current dimensions
        width, height = image.size
        
        # Crop to square from center
        min_dim = min(width, height)
        left = (width - min_dim) / 2
        top = (height - min_dim) / 2
        right = (width + min_dim) / 2
        bottom = (height + min_dim) / 2
        image = image.crop((left, top, right, bottom))
        
        # Resize to max 500x500
        image = image.resize((500, 500), Image.Resampling.LANCZOS)
        
        # Save to BytesIO
        output = BytesIO()
        
        # Determine format
        original_name = uploaded_file.name.lower()
        if original_name.endswith('.png'):
            image.save(output, format='PNG', optimize=True)
            content_type = 'image/png'
            extension = '.png'
        elif original_name.endswith('.gif'):
            # For GIF, we keep it as is if it's animated, otherwise convert to PNG
            image.save(output, format='PNG', optimize=True)
            content_type = 'image/png'
            extension = '.png'
        elif original_name.endswith('.webp'):
            image.save(output, format='WEBP', quality=85)
            content_type = 'image/webp'
            extension = '.webp'
        else:
            # Default to JPEG
            image.save(output, format='JPEG', quality=85, optimize=True)
            content_type = 'image/jpeg'
            extension = '.jpg'
        
        output.seek(0)
        
        # Create new filename with processed extension
        new_name = uploaded_file.name
        if '.' in new_name:
            new_name = new_name.rsplit('.', 1)[0] + extension
        else:
            new_name = new_name + extension
        
        return ContentFile(output.read(), name=new_name)
    
    except Exception:
        # If anything goes wrong, return the original file
        return uploaded_file
