"""
Utility functions for the accounts app.

This module provides reusable helper functions for user management,
including automatic username generation with collision detection.
"""

import re
import secrets
import unicodedata

from django.apps import apps
from django.contrib.auth import get_user_model


def generate_unique_username(first_name: str, last_name: str) -> str:
    """
    Generate a unique username from a user's first and last name.

    The username is generated by:
    1. Lowercasing both names
    2. Normalizing unicode characters (e.g., accented chars → ASCII)
    3. Removing all spaces and non-alphanumeric characters
    4. Appending a random 4-digit numeric suffix
    5. Checking the database for collisions and retrying if necessary

    Args:
        first_name: The user's first name.
        last_name: The user's last name.

    Returns:
        A unique, never-before-used username string.
    """
    UserModel = get_user_model()

    # Step 1: Normalize unicode and lowercase
    base = f"{first_name} {last_name}".lower()
    base = unicodedata.normalize("NFKD", base)
    base = base.encode("ascii", "ignore").decode("ascii")

    # Step 2: Strip spaces and non-alphanumeric characters
    base = re.sub(r"[^a-z0-9]", "", base)

    # Step 3: Ensure we have at least some characters
    if not base:
        base = "user"

    # Step 4: Generate a unique username with collision detection
    max_attempts = 100
    for _ in range(max_attempts):
        suffix = secrets.randbelow(9000) + 1000  # 1000–9999
        username = f"{base}{suffix}"
        if not UserModel.objects.filter(username=username).exists():
            return username

    # Fallback (extremely unlikely): use timestamp as suffix
    import time
    return f"{base}{int(time.time())}"
