"""
Utility functions for the accounts app.

This module provides reusable helper functions for user management,
including automatic username generation with collision detection.
"""

import re
import unicodedata
from datetime import datetime

from django.apps import apps
from django.contrib.auth import get_user_model


def generate_unique_username(first_name: str, last_name: str, year: int = None) -> str:
    """
    Generate a unique username from a user's first and last name.

    The username is generated by:
    1. Removing all spaces from the combined full name
    2. Appending the registration year (4 digits)
    3. Appending a sequential number (3 digits, zero-padded)

    Example: David Okonkwo, 2026, 1st user -> DavidOkonkwo2026001

    Args:
        first_name: The user's first name.
        last_name: The user's last name.
        year: The registration year (defaults to current year).

    Returns:
        A unique, never-before-used username string.
    """
    UserModel = get_user_model()

    if year is None:
        year = datetime.now().year

    # Step 1: Normalize unicode and remove spaces
    base = f"{first_name} {last_name}".strip()
    base = unicodedata.normalize("NFKD", base)
    base = base.encode("ascii", "ignore").decode("ascii")
    base = re.sub(r"\s+", "", base)  # Remove all spaces
    base = re.sub(r"[^a-zA-Z0-9]", "", base)  # Remove special characters

    # Step 2: Ensure we have at least some characters
    if not base:
        base = "User"

    # Step 3: Find the next sequential number for this year+base combination
    prefix = f"{base}{year}"
    existing_count = UserModel.objects.filter(username__startswith=prefix).count()
    seq = existing_count + 1

    # Step 4: Generate username with collision detection
    max_attempts = 100
    for _ in range(max_attempts):
        username = f"{prefix}{seq:03d}"
        if not UserModel.objects.filter(username=username).exists():
            return username
        seq += 1

    # Fallback (extremely unlikely): use timestamp as suffix
    import time
    return f"{prefix}{int(time.time())}"


def generate_unique_username_legacy(first_name: str, last_name: str) -> str:
    """
    Legacy username generator for backwards compatibility.
    Uses random 4-digit suffix.
    """
    UserModel = get_user_model()

    base = f"{first_name} {last_name}".lower()
    base = unicodedata.normalize("NFKD", base)
    base = base.encode("ascii", "ignore").decode("ascii")
    base = re.sub(r"[^a-z0-9]", "", base)

    if not base:
        base = "user"

    max_attempts = 100
    for _ in range(max_attempts):
        import secrets
        suffix = secrets.randbelow(9000) + 1000
        username = f"{base}{suffix}"
        if not UserModel.objects.filter(username=username).exists():
            return username

    import time
    return f"{base}{int(time.time())}"
