# Generated by Django 6.0.7 on 2026-07-24 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generate_usernames(apps, schema_editor):
    """Generate unique usernames for existing users."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for user in CustomUser.objects.all():
        name_parts = user.full_name.strip().split()
        first_name = name_parts[0] if name_parts else ""
        last_name = " ".join(name_parts[1:]) if len(name_parts) > 1 else ""
        base = f"{first_name}{last_name}".lower()
        # Remove non-alphanumeric characters
        import re
        base = re.sub(r'[^a-z0-9]', '', base)
        if not base:
            base = "user"
        # Ensure uniqueness with suffix
        suffix = 1
        while CustomUser.objects.filter(username=f"{base}{suffix}").exists():
            suffix += 1
        user.username = f"{base}{suffix}"
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Step 1: Add username field as nullable first (temporarily)
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                null=True,
                verbose_name='username',
                help_text='Required. 150 characters or fewer. Auto-generated from your name.',
                error_messages={'unique': 'A user with that username already exists.'},
            ),
            preserve_default=False,
        ),
        # Step 2: Populate usernames for existing users
        migrations.RunPython(
            generate_usernames,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Alter username to remove null constraint (now all rows have values)
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                verbose_name='username',
                help_text='Required. 150 characters or fewer. Auto-generated from your name.',
                error_messages={'unique': 'A user with that username already exists.'},
            ),
            preserve_default=False,
        ),
        # Step 4: Create SecurityQuestion model
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('birth_city', 'In what city were you born?'), ('first_school', 'What was the name of your first school?'), ('favorite_food', 'What is your favorite food?'), ('childhood_friend', 'Who was your childhood best friend?'), ('dream_job', 'What was your dream job as a child?'), ('favorite_book', 'What was your favorite book growing up?'), ('first_car', 'What was your first car or bicycle?')], help_text='Select a security question from the predefined list.', max_length=50, verbose_name='security question')),
                ('hashed_answer', models.CharField(help_text='The answer to the security question, stored securely hashed.', max_length=255, verbose_name='hashed answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'security question',
                'verbose_name_plural': 'security questions',
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_security_question')],
            },
        ),
    ]
