# Generated by Django 6.0.7 on 2026-07-26 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verified_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4, verbose_name='last 4 digits')),
                ('expiry', models.CharField(max_length=5, verbose_name='expiry date')),
                ('icon', models.CharField(default='💳', max_length=10, verbose_name='card icon')),
                ('is_default', models.BooleanField(default=False, verbose_name='default card')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved card',
                'verbose_name_plural': 'saved cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='NGN', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('success', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('payment_method', models.CharField(max_length=20, verbose_name='payment method')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date'],
            },
        ),
    ]
