# Generated by Django 6.0.7 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_savedcard_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_delivery_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Used to prefill delivery details during checkout.",
                verbose_name="default delivery address",
            ),
        ),
    ]
