# Generated by Django 6.0.7 on 2026-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_regenerate_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Requires the user to change their password on next login.', verbose_name='must change password'),
        ),
    ]
