# Generated by Django 6.0.7 on 2026-08-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPER_STAFF', 'Super Staff'), ('FARM_MANAGER', 'Farm Manager'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], default='CUSTOMER', help_text="Determines the user's permissions and access level.", max_length=20, verbose_name='role'),
        ),
    ]
