# Generated by Django 6.0.7 on 2026-08-18 09:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_super_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_upload_to, verbose_name='profile picture'),
        ),
    ]
