# Generated by Django 6.0.7 on 2026-08-20 04:30
#
# Purely additive: adds the `account_id` column with a blank default.
# Existing rows are NOT modified - no username is regenerated and no password
# is touched. Existing accounts simply keep account_id = "" (they predate
# random account IDs). Only accounts created after this migration get a value.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_update_profile_picture_upload_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, default='', help_text="The random alphanumeric segment of the auto-generated username (the part after 'TIF'). Blank for accounts created before random account IDs were introduced, and for usernames set explicitly by an administrator.", max_length=16, verbose_name='account ID'),
        ),
    ]
