# Generated by Django 6.0.7 on 2026-08-21

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sample_data',
            field=models.BooleanField(_("sample data"), default=False),
        ),
    ]
