# Generated by Django 6.0.7 on 2026-07-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page')], help_text='The section of the website this content belongs to', max_length=50, unique=True, verbose_name='section')),
                ('title', models.CharField(help_text='Title for this section', max_length=200, verbose_name='title')),
                ('content', models.TextField(help_text='Main content for this section (HTML allowed)', verbose_name='content')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site contents',
                'ordering': ['section'],
            },
        ),
    ]
