# Generated by Django 6.0.7 on 2026-07-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('faq', 'FAQ (Frequently Asked Questions)'), ('delivery_info', 'Delivery Information'), ('terms_privacy', 'Terms & Privacy Policy'), ('return_refund', 'Return & Refund Policy'), ('homepage_hero', 'Homepage Hero Text'), ('shop_banner', 'Shop Announcement Banner'), ('business_hours', 'Business Hours'), ('social_media', 'Social Media Links')], help_text='The section of the website this content belongs to', max_length=50, unique=True, verbose_name='section'),
        ),
    ]
