# Generated by Django 6.0.7 on 2026-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_sitecontent_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumOrderAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount in Naira (₦). Set to 0 to disable.', max_digits=10, verbose_name='minimum amount')),
                ('enabled', models.BooleanField(default=True, help_text='Whether to enforce minimum order amount', verbose_name='enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'minimum order amount',
                'verbose_name_plural': 'minimum order amount',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack (Card Payment)'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], help_text='The payment method to enable/disable', max_length=50, unique=True, verbose_name='payment method')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this payment method is available to customers', verbose_name='enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment method setting',
                'verbose_name_plural': 'payment method settings',
                'ordering': ['payment_method'],
            },
        ),
    ]
