# Generated by Django 6.0.7 on 2026-08-05

import re
from urllib.parse import urlparse

from django.db import migrations, models


PLATFORM_HOSTS = {
    "facebook_url": ("facebook.com", "fb.com"),
    "instagram_url": ("instagram.com",),
    "twitter_url": ("twitter.com", "x.com"),
    "tiktok_url": ("tiktok.com",),
    "whatsapp_url": ("whatsapp.com", "wa.me"),
}


def migrate_social_media_urls(apps, schema_editor):
    SiteContent = apps.get_model("admin_dashboard", "SiteContent")
    url_pattern = re.compile(r'https?://[^\s<>"\']+')

    for social_media in SiteContent.objects.filter(section="social_media"):
        updates = {}
        for url in url_pattern.findall(social_media.content or ""):
            hostname = urlparse(url).hostname or ""
            hostname = hostname.lower().removeprefix("www.")
            for field_name, domains in PLATFORM_HOSTS.items():
                if hostname in domains or hostname.endswith(tuple(f".{domain}" for domain in domains)):
                    if not getattr(social_media, field_name):
                        updates[field_name] = url
                    break
        if updates:
            SiteContent.objects.filter(pk=social_media.pk).update(**updates)


def reverse_migrate_social_media_urls(apps, schema_editor):
    # The original text content remains untouched, so reversing only removes structured values.
    SiteContent = apps.get_model("admin_dashboard", "SiteContent")
    SiteContent.objects.filter(section="social_media").update(
        facebook_url="",
        instagram_url="",
        twitter_url="",
        tiktok_url="",
        whatsapp_url="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_auditlogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="content",
            field=models.TextField(blank=True, help_text="Main content for this section (HTML allowed)", verbose_name="content"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram URL"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="tiktok_url",
            field=models.URLField(blank=True, verbose_name="TikTok URL"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter/X URL"),
        ),
        migrations.AddField(
            model_name="sitecontent",
            name="whatsapp_url",
            field=models.URLField(blank=True, verbose_name="WhatsApp URL"),
        ),
        migrations.RunPython(migrate_social_media_urls, reverse_migrate_social_media_urls),
    ]
