# Generated by Django 6.0.7 on 2026-08-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_sitecontent_social_media_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('same_day', 'Same Day Delivery'), ('standard', 'Standard Delivery'), ('economy', 'Economy Delivery')], max_length=30, unique=True, verbose_name='code')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='delivery price')),
                ('estimated_days', models.PositiveSmallIntegerField(default=3, verbose_name='estimated delivery days')),
                ('notes', models.TextField(blank=True, verbose_name='delivery notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'delivery option',
                'verbose_name_plural': 'delivery options',
                'ordering': ['estimated_days', 'price'],
            },
        ),
    ]
