# Generated by Django 6.0.7 on 2026-08-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_payment_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(blank=True, null=True, verbose_name='Monday open')),
                ('monday_close', models.TimeField(blank=True, null=True, verbose_name='Monday close')),
                ('monday_is_closed', models.BooleanField(default=False, verbose_name='Monday closed')),
                ('tuesday_open', models.TimeField(blank=True, null=True, verbose_name='Tuesday open')),
                ('tuesday_close', models.TimeField(blank=True, null=True, verbose_name='Tuesday close')),
                ('tuesday_is_closed', models.BooleanField(default=False, verbose_name='Tuesday closed')),
                ('wednesday_open', models.TimeField(blank=True, null=True, verbose_name='Wednesday open')),
                ('wednesday_close', models.TimeField(blank=True, null=True, verbose_name='Wednesday close')),
                ('wednesday_is_closed', models.BooleanField(default=False, verbose_name='Wednesday closed')),
                ('thursday_open', models.TimeField(blank=True, null=True, verbose_name='Thursday open')),
                ('thursday_close', models.TimeField(blank=True, null=True, verbose_name='Thursday close')),
                ('thursday_is_closed', models.BooleanField(default=False, verbose_name='Thursday closed')),
                ('friday_open', models.TimeField(blank=True, null=True, verbose_name='Friday open')),
                ('friday_close', models.TimeField(blank=True, null=True, verbose_name='Friday close')),
                ('friday_is_closed', models.BooleanField(default=False, verbose_name='Friday closed')),
                ('saturday_open', models.TimeField(blank=True, null=True, verbose_name='Saturday open')),
                ('saturday_close', models.TimeField(blank=True, null=True, verbose_name='Saturday close')),
                ('saturday_is_closed', models.BooleanField(default=False, verbose_name='Saturday closed')),
                ('sunday_open', models.TimeField(blank=True, null=True, verbose_name='Sunday open')),
                ('sunday_close', models.TimeField(blank=True, null=True, verbose_name='Sunday close')),
                ('sunday_is_closed', models.BooleanField(default=False, verbose_name='Sunday closed')),
                ('notes', models.TextField(blank=True, help_text='Special hours, holiday notices, or other remarks', verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('site_content', models.OneToOneField(help_text='The SiteContent record this business hours data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_detail', to='admin_dashboard.sitecontent', verbose_name='site content')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
            },
        ),
    ]
