# Generated by Django 6.0.7 on 2026-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_migrate_business_hours_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
    ]
