# Generated by Django 6.0.7 on 2026-08-11 22:54

from django.db import migrations


def create_default_site_content_sections(apps, schema_editor):
    SiteContent = apps.get_model('admin_dashboard', 'SiteContent')
    sections = [
        ('homepage_hero', 'Homepage Hero', ''),
        ('shop_banner', 'Shop Banner', ''),
        ('about', 'About Us', '<p>Tell your farm story here.</p>'),
        ('contact', 'Contact Us', '<p>Add your phone, email, and address here.</p>'),
        ('faq', 'Frequently Asked Questions', '<p><strong>Q:</strong> Your question here?<br><strong>A:</strong> Your answer here.</p>'),
        ('delivery_info', 'Delivery Information', '<p>Add your delivery zones, pricing, and timing here.</p>'),
        ('terms_privacy', 'Terms & Privacy Policy', '<p>Add your terms and privacy policy here.</p>'),
        ('return_refund', 'Return & Refund Policy', '<p>Add your return and refund policy here.</p>'),
        ('business_hours', 'Business Hours', '<p>Monday - Friday: 8:00 AM - 6:00 PM<br>Saturday: 9:00 AM - 4:00 PM<br>Sunday: Closed</p>'),
        ('social_media', 'Social Media', '<p>Add your social media links in the form below.</p>'),
    ]
    for section, title, content in sections:
        SiteContent.objects.get_or_create(
            section=section,
            defaults={'title': title, 'content': content},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_add_sitecontent_is_sample'),
    ]

    operations = [
        migrations.RunPython(create_default_site_content_sections, migrations.RunPython.noop),
    ]
