# Generated by Django 6.0.7 on 2026-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_delivery_address_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Stock level below which product is considered low stock', verbose_name='low stock threshold'),
        ),
    ]
