# Generated by Django 6.0.7 on 2026-08-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.contactmessage', verbose_name='parent message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin/Staff')], default='customer', max_length=20, verbose_name='sender type'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups messages in the same conversation', max_length=50, null=True, verbose_name='thread id'),
        ),
    ]
