# Generated by Django 6.0.7 on 2026-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contactmessage_parent_contactmessage_sender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/', verbose_name='image'),
        ),
    ]
