# Generated by Django 6.0.7 on 2026-08-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0012_add_analytics_indexes'),
        ('shop', '0013_increase_image_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_batch',
            field=models.ForeignKey(blank=True, help_text='Optional: link this product to a farm batch for automatic stock tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_products', to='farm_management.batch', verbose_name='linked batch'),
        ),
    ]
