# Generated by Django 6.0.7 on 2026-08-21

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_linked_batch_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sample_data',
            field=models.BooleanField(_("sample data"), default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_sample_data',
            field=models.BooleanField(_("sample data"), default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_sample_data',
            field=models.BooleanField(_("sample data"), default=False),
        ),
    ]
