# Generated by Django 6.0.7 on 2026-07-27 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('species', models.CharField(choices=[('catfish', 'Catfish'), ('tilapia', 'Tilapia'), ('broiler', 'Broiler (Poultry)'), ('layer', 'Layer (Poultry)')], max_length=20, verbose_name='species')),
                ('initial_count', models.PositiveIntegerField(verbose_name='initial count')),
                ('current_stock', models.PositiveIntegerField(verbose_name='current stock')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('season', models.CharField(choices=[('rainy', 'Rainy Season'), ('dry', 'Dry Season')], max_length=10, verbose_name='season')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100, verbose_name='feed type')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='supplier')),
                ('quantity_on_hand_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantity on hand (kg)')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cost per kg')),
                ('reorder_point_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='reorder point (kg)')),
            ],
            options={
                'verbose_name': 'feed inventory',
                'verbose_name_plural': 'feed inventory',
                'ordering': ['feed_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('note', models.TextField(verbose_name='note')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activity_logs/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='farm_management.batch', verbose_name='batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'daily activity log',
                'verbose_name_plural': 'daily activity logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('feed_type', models.CharField(max_length=100, verbose_name='feed type')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='quantity (kg)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'feed log',
                'verbose_name_plural': 'feed logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('average_weight_kg', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='average weight (kg)')),
                ('sample_size', models.PositiveIntegerField(help_text='Number of animals sampled for this average', verbose_name='sample size')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'growth record',
                'verbose_name_plural': 'growth records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='harvest date')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='quantity sold')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total revenue')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'harvest record',
                'verbose_name_plural': 'harvest records',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('medicine_name', models.CharField(max_length=150, verbose_name='medicine name')),
                ('dosage', models.CharField(max_length=100, verbose_name='dosage')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('administered_by', models.CharField(blank=True, max_length=150, verbose_name='administered by')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='health_logs/', verbose_name='photo')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'health/medication log',
                'verbose_name_plural': 'health/medication logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('cause', models.CharField(blank=True, max_length=200, verbose_name='cause')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_logs', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'mortality log',
                'verbose_name_plural': 'mortality logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('vaccine_name', models.CharField(max_length=150, verbose_name='vaccine name')),
                ('dosage', models.CharField(max_length=100, verbose_name='dosage')),
                ('administered_by', models.CharField(blank=True, max_length=150, verbose_name='administered by')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'vaccination record',
                'verbose_name_plural': 'vaccination records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH level')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperature (°C)')),
                ('oxygen_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='oxygen level (mg/L)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_logs', to='farm_management.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'water quality log',
                'verbose_name_plural': 'water quality logs',
                'ordering': ['-date'],
            },
        ),
    ]
