# Generated by Django 6.0.7 on 2026-08-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0005_remove_feedlog_feed_type_alter_feedlog_feed_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlog',
            name='feed_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_logs', to='farm_management.feedinventory', verbose_name='feed inventory'),
        ),
    ]
