# Generated by Django 6.0.7 on 2026-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0009_feedinventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='dailyactivitylog',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='feedinventory',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='healthmedicationlog',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='mortalitylog',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='species',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
        migrations.AddField(
            model_name='waterqualitylog',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
    ]
