# Generated by Django 6.0.7 on 2026-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0010_batch_is_sample_category_is_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinventory',
            name='compatible_batches',
            field=models.ManyToManyField(blank=True, help_text='Batches this feed is suitable for. Based on category/species match.', related_name='compatible_feed_inventory', to='farm_management.batch', verbose_name='compatible batches'),
        ),
    ]
