# Generated by Django 6.0.7 on 2026-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0011_add_feedinventory_compatible_batches'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedlog',
            index=models.Index(fields=['batch', 'date'], name='feedlog_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='growthrecord',
            index=models.Index(fields=['batch', 'date'], name='growthrecord_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='healthmedicationlog',
            index=models.Index(fields=['batch', 'date'], name='health_log_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalitylog',
            index=models.Index(fields=['batch', 'date'], name='mortalitylog_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['batch', 'date'], name='vaccination_batch_date_idx'),
        ),
    ]
