# Generated by Django 6.0.7 on 2026-08-19 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0012_add_analytics_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('electricity', 'Electricity'), ('labor', 'Labor'), ('sawdust', 'Sawdust')], max_length=20, verbose_name='expense type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('date_incurred', models.DateField(verbose_name='date incurred')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm_management.batch', verbose_name='batch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'farm expense',
                'verbose_name_plural': 'farm expenses',
                'ordering': ['-date_incurred', '-created_at'],
                'indexes': [models.Index(fields=['expense_type', 'date_incurred'], name='farmexpense_type_date_idx')],
            },
        ),
    ]
