# Generated by Django 6.0.7 on 2026-08-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0013_add_farm_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm_management.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='farmexpense',
            name='expense_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('labor', 'Labor'), ('sawdust', 'Sawdust'), ('supplier_purchase', 'Animal/Stock Purchase')], max_length=20, verbose_name='expense type'),
        ),
    ]
