# Generated by Django 6.0.7 on 2026-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0014_add_supplier_to_farmexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpense',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='sample data'),
        ),
    ]
