# Generated by Django 6.0.7 on 2026-08-19 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0015_add_is_sample_to_farmexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_logs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='healthmedicationlog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_logs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='mortalitylog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_logs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
    ]
