# Generated by Django 6.0.7 on 2026-08-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0016_add_recorded_by_to_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmexpense',
            name='expense_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('labor', 'Labor'), ('sawdust', 'Sawdust'), ('supplier_purchase', 'Animal/Stock Purchase'), ('feed_purchase', 'Feed Purchase')], max_length=20, verbose_name='expense type'),
        ),
    ]
