# Generated by Django 6.0.7 on 2026-08-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0017_add_feed_purchase_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpense',
            name='feed_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm_management.feedinventory', verbose_name='feed inventory'),
        ),
        migrations.AddField(
            model_name='farmexpense',
            name='quantity_purchased_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='quantity purchased (kg)'),
        ),
    ]
