# Generated by Django 6.0.7 on 2026-08-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0018_add_feed_purchase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmexpense',
            name='custom_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='custom label'),
        ),
        migrations.AlterField(
            model_name='farmexpense',
            name='expense_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('labor', 'Labor'), ('sawdust', 'Sawdust'), ('supplier_purchase', 'Animal/Stock Purchase'), ('feed_purchase', 'Feed Purchase'), ('other', 'Other')], max_length=20, verbose_name='expense type'),
        ),
    ]
