# Generated by Django 6.0.7 on 2026-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'New Order'), ('payment', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('user', 'New User Registered'), ('system', 'System')], max_length=20, verbose_name='type')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='related object id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
