# Generated by Django 6.0.7 on 2026-08-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('payment', 'Payment Received'), ('low_stock', 'Low Stock Alert'), ('user', 'New User Registered'), ('system', 'System'), ('batch_alert', 'Batch Alert')], max_length=20, verbose_name='type'),
        ),
    ]
